# Layer 2 of 4 — the shared home core. Runs on EVERY host, both platforms.
#
# The rule for this directory: if it would not work unchanged on both macOS and
# Linux, it does not belong here. That constraint is what makes the Mac and both
# Linux VMs give the identical shell, git and editor; anything platform-bound
# goes one layer out, into the platform home entry that imports this file:
#   modules/darwin/home -> this + default-browser, hammerspoon, conda,
#                          login-shell, stale-cwd
#   modules/nixos/home  -> this (nothing Linux-only yet)
#
# Everything here is unconditional; optional behaviour is declared as an hn.*
# toggle in ./features.nix and gated inside its own module, so a host that has
# not opted in contributes nothing to the closure.
#
# Identity (username, homeDirectory, stateVersion) is not set here — it comes
# from the global `identity` in flake.nix via lib/mk-home.nix.
{ ... }:

{
  imports = [
    # Option DECLARATIONS only (no config), so every host can read hn.* even
    # when the consuming module is inert.
    ./features.nix

    # Files copied verbatim, as opposed to generated by a programs.* module.
    ./files.nix

    # CLI tools from nixpkgs. GUI apps are Homebrew's job (see
    # modules/darwin/homebrew); language runtimes are mise's (programs/mise.nix).
    ./packages/development.nix
    ./packages/system.nix

    # One file per program. Each owns its own config and its own gating, so
    # this list stays a flat inventory with no conditionals.
    ./programs/git.nix
    ./programs/ssh.nix
    ./programs/zsh.nix
    ./programs/starship.nix
    ./programs/neovim.nix
    ./programs/tmux.nix
    ./programs/direnv.nix
    ./programs/fzf.nix
    ./programs/eza.nix
    ./programs/zoxide.nix
    ./programs/nh.nix
    ./programs/atuin.nix
    ./programs/docker.nix # CLI-only docker + remote-engine contexts (hn.remoteDocker)

    # Toolchains. mise owns runtime VERSIONS; the three below are work-specific
    # and inert unless hn.atlassian is set.
    ./programs/mise.nix
    ./programs/maven.nix
    ./programs/atlassian-sdk.nix
    ./programs/atlassian-mise.nix
  ];
}
