# Static dotfiles managed by home-manager, shared across all hosts.
#
# Use this for files that are just *copied/symlinked* into place (as opposed to
# program config generated by a `programs.*` module). Point `source` at a file
# checked in beside this one, or use `text` for inline content.
#
#   home.file.".config/foo/bar.conf".source = ./files/bar.conf;
#   xdg.configFile."foo/baz.toml".text = "...";
#
# Empty by default — nothing to symlink yet. Add entries as needed.
{ ... }:

{
  home.file = { };
}
