# Verbatim dotfiles, for every host.
#
# For files with no home-manager module to generate them. Prefer a `programs.*`
# module when one exists — it gives typed options and merges with other modules,
# where a raw file silently wins over everything.
#
#   home.file.".config/foo/bar.conf".source = ./files/bar.conf;  # checked in here
#   xdg.configFile."foo/baz.toml".text = "...";                  # inline
#
# Note these become read-only symlinks into the nix store, so a tool that wants
# to rewrite its own config file will fail against them.
#
# Currently empty — every dotfile in use is generated by a programs.* module.
{ ... }:

{
  home.file = { };
}
