# Hammerspoon: Lua automation for the things only an event-driven daemon can do
# — react to a volume mounting, route a link by hostname, notice its own config
# changing. Anything a dedicated app already covers well (window snapping ->
# rectangle, launcher/clipboard -> raycast, per-app IME -> input-source-pro)
# deliberately stays with that app.
#
# Layout: the Lua lives in ./hammerspoon/*.lua as real Lua files (editor tooling,
# no nix string escaping); this module only generates ~/.hammerspoon/init.lua,
# which publishes the nix-side settings as the global `HN` table and then
# requires each feature module. Each feature module returns early when its
# toggle is off, so init.lua is the same shape on every host.
#
# The app itself is installed via Homebrew (see modules/darwin/homebrew/
# casks/system.nix). On first launch, grant Hammerspoon Accessibility
# permission (System Settings → Privacy & Security → Accessibility) — the
# clipboard key watcher needs it, and it can't be granted declaratively.
{
  config,
  lib,
  ...
}:

let
  cfg = config.hn.hammerspoon;
  hsDir = "${config.home.homeDirectory}/.hammerspoon";

  # Settings handed to the Lua side as the global `HN`. Kept in one place so a
  # feature module never has to be regenerated by nix — only this table changes.
  hnTable = {
    clipboardSounds = {
      inherit (cfg.clipboardSounds) enable;
      copyFile = "${hsDir}/sounds/copy.mp3";
      pasteFile = "${hsDir}/sounds/paste.mp3";
    };
    volumeWatch = {
      inherit (cfg.volumeWatch)
        enable
        volumes
        notify
        onMount
        onUnmount
        ;
    };
    urlRouter = {
      inherit (cfg.urlRouter) enable fallback;
      rules = map (r: { inherit (r) hosts bundleId; }) cfg.urlRouter.rules;
    };
  };
in
lib.mkIf cfg.enable {
  # Making Hammerspoon the system http/https handler is what lets url-router.lua
  # see links at all. mkDefault so a host can still point the handler elsewhere.
  hn.defaultBrowser = lib.mkIf cfg.urlRouter.enable {
    handler = lib.mkDefault "hammerspoon";
    app = lib.mkDefault "/Applications/Hammerspoon.app";
  };

  # Vendored sound assets, placed next to the config.
  home.file.".hammerspoon/sounds/copy.mp3".source = ./hammerspoon/copy.mp3;
  home.file.".hammerspoon/sounds/paste.mp3".source = ./hammerspoon/paste.mp3;

  # Feature modules. Hammerspoon puts ~/.hammerspoon on package.path, so these
  # are require()d by basename from init.lua.
  home.file.".hammerspoon/toast.lua".source = ./hammerspoon/toast.lua;
  home.file.".hammerspoon/autoreload.lua".source = ./hammerspoon/autoreload.lua;
  home.file.".hammerspoon/clipboard-sounds.lua".source = ./hammerspoon/clipboard-sounds.lua;
  home.file.".hammerspoon/volume-watch.lua".source = ./hammerspoon/volume-watch.lua;
  home.file.".hammerspoon/url-router.lua".source = ./hammerspoon/url-router.lua;

  home.file.".hammerspoon/init.lua".text = ''
    -- Generated by home-manager from modules/darwin/home/hammerspoon.nix.
    -- Edit that module (or the .lua files beside it), not this file: the next
    -- `darwin-rebuild switch` overwrites it.

    HN = ${lib.generators.toLua { } hnTable}

    -- Launch at login. Hammerspoon is load-bearing once it handles http/https or
    -- watches for a drive, and this preference is otherwise a GUI checkbox.
    hs.autoLaunch(${lib.boolToString cfg.autoLaunch})

    -- Local mach-port control channel, which is what makes `hs -c '<lua>'`
    -- work from a shell (/opt/homebrew/bin/hs ships inside the app bundle).
    -- Without it there is no way to poke a running Hammerspoon except the GUI
    -- console.
    require("hs.ipc")

    -- Toast first: the feature modules below call the global it defines.
    Toast = require("toast")

    ${lib.optionalString cfg.autoReload ''require("autoreload")''}
    require("clipboard-sounds")
    require("volume-watch")
    require("url-router")

    -- Brief confirmation that the (re)load actually took, which is the whole
    -- point of autoreload.
    Toast({ title = "Hammerspoon", detail = "config reloaded", kind = "info" })
  '';
}
